exerciseApp/urls.py
from django.urls import path
from .views import *

app_name = 'exerciseApp'
urlpatterns = [
    path('exercise_list/',exercise_list, name="exercise_list"),
    # path('test/',test, name="test"),
    path('ex/<str:exercise_name>/',exercise_detail, name='exercise_detail'), #Load everything by name
    path('submission/<str:exercise_name>/', submission_detail, name='submission_detail'),

    #admin review urls
    path('review_list/', exercises_list, name='exercises_list'),
    path('exercise/<str:exercise_title>/', exercise_submissions, name='exercise_submissions'),
    path('submissions/<int:submission_id>/', submission_details, name='submission_details'),
    path('submit-review/<int:submission_id>/', submit_review, name='submit_review'),

    #user reviews url
    path('my-reviews/',user_reviews, name='user_reviews'),
]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import register_view,logout_view,login_view
from django.contrib.auth import views as auth_views
# from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('subscribtion.urls')),
    path('',include('introToHTML_app.urls')), 
    path('',include('introToCSS_app.urls')),
    path('',include('blog_ttrial.urls')),
    path('', include('ProgrammingLanguages_app.urls')),
    path('', include('exerciseApp.urls')),
    path('', include('quizApp.urls')),
    



    # path('',code_editor_view, name="home"),
    # path('index/',index, name="index"),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

exerciseApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.utils import timezone
from cloudinary_storage.storage import MediaCloudinaryStorage
from cloudinary.models import CloudinaryField   


class Exercise(models.Model):
    exercise_name = models.CharField(max_length=255, unique=True,
                                 validators=[RegexValidator(regex='^[a-zA-Z0-9_-]+$',
                                                            message='Only alphanumeric characters, underscores, and hyphens are allowed.')], blank=True, null=True) #Load by exercise name
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    instructions = models.TextField(blank=True)  #Detailed instructions for the exercise
    reference_code = models.TextField()  # 

    def __str__(self):
        return self.title

class CodeSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    code = models.TextField()
    submission_time = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0) #Score for the submission

    def __str__(self):
        return f"Submission by {self.user.username} for {self.exercise.title}"
    
class CompletedExercise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    completed_time = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username} - {self.exercise.title} - {self.score}"
    
class SpecialExercise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=90)
    type=models.CharField(max_length=90)
    code = models.TextField()
    verified = models.BooleanField(default=False, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "SpecialExercises"

    def __str__(self):
        return self.title
    
class ExerciseRemarks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise_title = models.CharField(max_length=200)
    remarks = models.TextField()
    score = models.IntegerField()
    code = models.TextField(default="console.log('Your code')")
    date = models.DateTimeField(default=timezone.now)
    
    def status(self):
        if self.score >= 70:
            return "passed"
        elif self.score >= 50:
            return "fair"
        return "failed"

    def __str__(self):
        return f"Feedback for {self.exercise_title} by {self.user.username}"
    
class VideoUpload(models.Model):
    title = models.CharField(max_length=200)
    description=models.TextField(blank=True, null=True)
    video=CloudinaryField(resource_type='video', folder='Videos/')
    
    def __str__(self):
        return self.title
    
class ImageUpload(models.Model):
    title = models.CharField(max_length=200)
    description=models.TextField(blank=True, null=True)
    video=models.ImageField(upload_to='Images/', storage=MediaCloudinaryStorage())
    
    def __str__(self):
        return self.title

exerciseApp/forms.py
from django import forms
from .models import CodeSubmission

class CodeSubmissionForm(forms.ModelForm):
    class Meta:
        model = CodeSubmission
        fields = ['code']
       

exerciseApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Exercise, CodeSubmission
from .forms import CodeSubmissionForm
from difflib import SequenceMatcher
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Exercise, CodeSubmission
from .forms import CodeSubmissionForm
from .utils import compare_code  # Import the compare_code function
from django.http import HttpResponse,Http404
from quizApp.models import *
from django.contrib import messages

# @login_required(login_url="login")
# def exercise_list(request):
#     exercises = Exercise.objects.all()
#     print(f'Exercises are {exercises}')
#     return render(request, 'exercise_list.html', {'exercises': exercises})

# def test(request):
#     return HttpResponse("Hello world")



# @login_required(login_url="login")
# def exercise_detail(request, exercise_id):
#     exercise = get_object_or_404(Exercise, pk=exercise_id)

#     if request.method == 'POST':
#         form = CodeSubmissionForm(request.POST)
#         if form.is_valid():
#             submission = form.save(commit=False)
#             submission.user = request.user
#             submission.exercise = exercise
#             submission.save()

#             # Compare code using the imported function
#             comparison_result = compare_code(submission.code, exercise.reference_code)
#             submission.score = comparison_result['score']  # Access the score from the dict
#             submission.save()

#             return redirect('exerciseApp:submission_detail', submission_id=submission.id)
#     else:
#         form = CodeSubmissionForm()

#     return render(request, 'exercise_detail.html', {'exercise': exercise, 'form': form})

# @login_required(login_url="login")
# def submission_detail(request, submission_id):
#     submission = get_object_or_404(CodeSubmission, pk=submission_id, user=request.user)
#     return render(request, 'submission_detail.html', {'submission': submission})



from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Exercise, CodeSubmission, CompletedExercise
from .forms import CodeSubmissionForm
from .utils import compare_code  # Import the compare_code function
from django.urls import reverse
from django.db.models import F

@login_required(login_url="login")
def exercise_list(request):
    exercises = Exercise.objects.all()
    return render(request, 'exercise_list.html', {'exercises': exercises})

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Exercise, CodeSubmission, CompletedExercise
from .forms import CodeSubmissionForm

from django.urls import reverse
from quizApp.models import LeaderboardEntry # Add model from the other app
from django.db import transaction #Need transaction!
from django.db.models import Sum, F

@login_required(login_url="login")
@transaction.atomic
def exercise_detail(request, exercise_name):
    exercise = get_object_or_404(Exercise, exercise_name=exercise_name) #Load from name
    has_completed = CompletedExercise.objects.filter(user=request.user, exercise=exercise).exists()
    last_submission = CodeSubmission.objects.filter(user=request.user, exercise=exercise).order_by('-submission_time').first()
    num_attempts = CodeSubmission.objects.filter(user=request.user, exercise=exercise).count() #Get number of attempts
    can_try_again = False #Allow or deny to submit again

    # If the user has already completed the exercise, check if they're allowed to try again
    if has_completed:
        if last_submission and last_submission.score < 50 and num_attempts < 2:
            can_try_again = True
        else:
            return redirect('exerciseApp:submission_detail', exercise_name=exercise.exercise_name) #Access main view
    
    # Create form
    if request.method == 'POST':
        form = CodeSubmissionForm(request.POST)

        # Valid submission: create the objects and check it
        if form.is_valid():
            submission = form.save(commit=False)
            submission.user = request.user
            submission.exercise = exercise

            comparison_result = compare_code(submission.code, exercise.reference_code) # Run similarity and check

            submission.score = comparison_result['score']  # Access the score from the dict
            submission.save() #Set it to the current exercise

            #Check if quiz for adding in QuizSubmission
            #If it exists - it should create an entry
            print(f"Quiz is {exercise.exercise_name}")
            quizzes, created = Quiz.objects.get_or_create(
                quiz_name='exercises',
                defaults={
                    'title': 'Exercise',
                    'description': '',  # Empty description
                    'link': 'link'
                }
            )
            quizzes.save()
            quiz_submission, created = QuizSubmission.objects.get_or_create(user=request.user, quiz=quizzes)
            quiz_submission.total_score = F('total_score') + submission.score
            quiz_submission.save()
            #Update total score in LeaderboardEntry
            try:
                leaderboard_entry = LeaderboardEntry.objects.get(user=request.user)
                leaderboard_entry.total_score = F('total_score') + submission.score
                leaderboard_entry.save()
            except LeaderboardEntry.DoesNotExist:
                LeaderboardEntry.objects.create(user=request.user, total_score=submission.score)

            return redirect('exerciseApp:submission_detail', exercise_name=exercise.exercise_name) #Check main
        else:
            print("Inavlid Form")
    else:
        form = CodeSubmissionForm() #Load main form

    return render(request, 'exercise_detail.html', {
        'exercise': exercise,
        'form': form,
        'num_attempts': num_attempts, #Load the number of attempts
        'can_try_again': can_try_again #Let them load
        })

@login_required(login_url="login")
def submission_detail(request, exercise_name):
    exercise = get_object_or_404(Exercise, exercise_name=exercise_name)
    #Get all the previous code submission
    submission = CodeSubmission.objects.filter(user=request.user, exercise=exercise).order_by('-submission_time').first() #The code
    
    #Load the total score,
    try:
        total_score = LeaderboardEntry.objects.get(user=request.user).total_score
    except:
        total_score = None

    if submission == None: # Error where it does not exist
        return render(request, 'submission_detail.html', {'user': request.user}) #Access view
    else:
        correct_answer = exercise.reference_code #Load reference code
        
        #Example - load all codes or something that makes it work
        data_entries = CodeSubmission.objects.filter(user=request.user)

        leaderboard_entries = LeaderboardEntry.objects.order_by('-total_score')[:10]
        # quizzes = Quiz.objects.filter(quiz_name=exercise_name)
        recent_submission = QuizSubmission.objects.filter(user=request.user).latest('submission_time')
        recent_score = recent_submission.score
        total_score = QuizSubmission.objects.filter(user=request.user).aggregate(Sum('score'))['score__sum'] or 0
        leaderboard = LeaderboardEntry.objects.order_by('-total_score')
        rank = LeaderboardEntry.objects.filter(total_score__gt=LeaderboardEntry.objects.get(user=request.user).total_score).count() + 1
        
        context = {
        'submission': submission,
        'correct_answer': correct_answer, #Show user what the code is
        'total_score': total_score,
        'data_entries': data_entries,
        'leaderboard_entries':leaderboard_entries,
        'leaderboard':leaderboard,
        'rank':rank,
        'recent_score':recent_score,
        } #Add dashboard
        return render(request, 'submission_detail.html', context)
    


#Admin exercise handling
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import SpecialExercise, ExerciseRemarks
from quizApp.models import LeaderboardEntry
from django.http import JsonResponse
from django.views.decorators.http import require_POST
import json


@login_required(login_url="login")
def exercises_list(request):
    if request.user.is_staff:
        exercises = SpecialExercise.objects.values('title').distinct()
        return render(request, 'admin_reviews/exercises.html', {
            'exercises': [ex['title'] for ex in exercises]
        })
    else:
        return HttpResponse("You don't have the required permissions to access this page.")

@login_required(login_url="login")
def exercise_submissions(request, exercise_title):
    if request.user.is_staff:
        submissions = SpecialExercise.objects.filter(title=exercise_title, verified=False).select_related('user')
        return render(request, 'admin_reviews/users.html', {
            'exercise_title': exercise_title,
            'submissions': submissions
        })
    else:
        return HttpResponse("You don't have the required permissions to access this page.")


@login_required(login_url="login")
def submission_details(request, submission_id):
    if request.user.is_staff:
        try:
            submission = SpecialExercise.objects.get(id=submission_id)
            print(f"code is {submission.code}")
            # Get existing remarks if they exist
            try:
                remarks = ExerciseRemarks.objects.get(
                    user=submission.user,
                    exercise_title=submission.title
                )
                initial_score = remarks.score
                initial_remarks = remarks.remarks

exerciseApp/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}byteCub Exercises{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel="stylesheet" href="{% static 'assets/CSS/quiz/style.css' %}">
    
</head>
<body>
    <header>
        <h1>Exercise</h1>
        <nav>
            {% if user.is_authenticated %}
                <span>Welcome, {{ user.username }}!</span>
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'register' %}">Register</a>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2025 byteCub</p>
    </footer>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
  const codeEditor = document.querySelector('.code-editor');

  if (codeEditor) {
    codeEditor.addEventListener('input', function() {
      // Implement code highlighting here using libraries like Prism.js or Highlight.js
      // For example:
      // Prism.highlightElement(codeEditor);
      // The specific code will depend on the chosen library

      //Preserves Code - just keeps the same code.
    });
  }
});
    </script>
</body>
</html>

exerciseApp/templates/exercise_detail.html
{% extends "base2.html" %}

{% block content %}
  <h2>{{ exercise.title }}</h2>
  <p>{{ exercise.description }}</p>
  <p>Instructions: {{ exercise.instructions }}</p>

    <p>Attempts: {{ num_attempts }}</p>
    {% if num_attempts < 3 %}

    {% if num_attempts < 2 %}
        <p style="color: orangered">Submit code Below | {{num_attempts}} attempt left</p>
    {% else %}
        <p style="color: red">You've attempted the excercise. </p>
    {% endif %}
  <form method="post" style="width: 90%;">
    {% csrf_token %}
      <textarea id="code-editor" name="code" style="width: 100%;">{{ form.code.value }}</textarea>
    <button type="submit">Submit Code</button>
  </form>
    {% endif %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js"></script>
<script>
    var editor = CodeMirror.fromTextArea(document.getElementById("code-editor"), {
        mode: "python",
        theme: "default",
        lineNumbers: true,
        indentUnit: 4,
        indentWithTabs: true,
        lineWrapping: true,
        autofocus: true,
        styleActiveLine: true
    });
</script>
{% endblock %}

exerciseApp/templates/exercise_list.html
{% extends "base2.html" %}
{% block content %}
  <h2>Exercises</h2>
  <ul>
    {% for exercise in exercises %}
      <li><a href="{% url 'exerciseApp:exercise_detail' exercise.id %}">{{ exercise.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

exerciseApp/templates/submission_detail.html
{% extends "base2.html" %}

{% load static %}

{% block content %}
  <div class="container">
    <h2>Submission Details</h2>
    {% if submission %}
      <div class="row">
        <div class="col-md-6">
          <h3>Your Code</h3>
          <pre id="user-code">{{ submission.code }}</pre>
        </div>
        <div class="col-md-6">
          <h3>Correct Answer</h3>
          <pre id="correct-code">{{ correct_answer }}</pre>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p>Score: {{ submission.score }}</p>
        </div>
      </div>
    {% else %}
      <p>No submission has been made. Redirect back to the main page to get questions.</p>
    {% endif %}
  </div>

  <section class="leaderboard-section">
        <h3>Leaderboard</h3>
        <p>Your Rank: {{ rank }}</p>
        <ol>
            {% for entry in leaderboard %}
                <li>{{ entry.user.username }} - {{ entry.total_score }}</li>
            {% endfor %}
        </ol>
    </section>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js"></script>
  
  <style>
    /* Adjust to your desired theme */
    .CodeMirror {
      border: 1px solid #eee;
      height: auto;
      width: 100%;
      font-size: 14px;
      line-height: 1.4;
      background-color: #f9f9f9;
    }
    pre {
        background-color: black;
        color: white;
        border-radius: 5px;
        padding: 10px;
        font-family: monospace;
    }
  </style>
{% endblock %}